name: my-tests


on:
  push:
    branches: ["master"]
      
jobs:
  test_my_code:
    runs-on   : ubuntu-latest
    steps     :
      - name   : Git-Clone-my-repo
        uses   : actions/checkout@v3
      - run    : |
         cd $GITHUB_WORKSPACE
         python3 -m unittest test_tz2
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/$%7B%7B github.repository }}/commit/${{github.sha}}
         
        
        
      
    
