name: my-tests


on:
  push:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
      
jobs:
 test_my_code:
    runs-on   : ubuntu-latest
    
    steps     :
      - name   : Git-Clone-my-repo
        uses   : actions/checkout@v3
      - run    : |
         cd $GITHUB_WORKSPACE
         python3 -m unittest test_tz2
         exit 1
         
      - name: telegram bot
        if: ${{ success() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} создал коммит:
            Были внесены изменения: ${{ github.event.commits[0].message }}

            Изменения произошли в репозитории: ${{ github.repository }}
        
            СТАТУС ТЕСТА ПОСЛЕ КОММИТА: УСПЕШНО!

            Посмотреть изменения: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            
      - name: telegram bot
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} создал коммит:
            Были внесены изменения: ${{ github.event.commits[0].message }}

            Изменения произошли в репозитории: ${{ github.repository }}
        
            СТАТУС ТЕСТА ПОСЛЕ КОММИТА: ПРОВАЛ!

            Посмотреть изменения: https://github.com/${{ github.repository }}/commit/${{github.sha}} 
         
# telega1:
#  runs-on: ubuntu-latest
#  needs: [test_my_code]
#  steps:
#  - name: Git-Clone-my-repo
#    uses: actions/checkout@v3
#  - run: |
#      cd $GITHUB_WORKSPACE
#      python3 -m unittest test_tz2
#      
#  - name: telegram bot
#    uses: appleboy/telegram-action@master
#    with:
#      to: ${{ secrets.TELEGRAM_TO }}
#      token: ${{ secrets.TELEGRAM_TOKEN }}
#      message: |
#        ${{ github.actor }} создал коммит:
#        Были внесены изменения: ${{ github.event.commits[0].message }}

#        Изменения произошли в репозитории: ${{ github.repository }}
        
#        СТАТУС ТЕСТА ПОСЛЕ КОММИТА: УСПЕШНО!

#        Посмотреть изменения: https://github.com/${{ github.repository }}/commit/${{github.sha}}
 

        
        
      
    
